services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - leftovers-database-network
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMIAL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    networks:
      - leftovers-database-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${ENVIRONMENT}
    restart: unless-stopped
    networks:
      - leftovers-database-network
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "
      npm run migrations
      && npx nest start --watch
      "

volumes:
  local_pgdata:
  pgadmin-data:
  db_data:
    driver: local

networks:
  leftovers-database-network:
    driver: bridge

